on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - name: github-docs-to-wiki
            uses: cmbrose/github-docs-to-wiki@v0.24
            with: 
                githubToken: ${{ secrets.WIKI_ACTION_TOKEN }}
#           - uses: actions/checkout@master
#           - name: Sync Wiki
#             uses: joeizzard/action-wiki-sync@master
#             with:
#                 username: AbdullahAlfaraj
#                 access_token: ${{ secrets.WIKI_ACTION_TOKEN }}
#                 wiki_folder: wiki2/
#                 commit_username: 'AbdullahAlfaraj'
#                 commit_email: '7842232+AbdullahAlfaraj@users.noreply.github.com'
#                 commit_message: 'action: wiki sync'
            

